/**
 * DealRepository - CRUD operations for Deal model
 *
 * Provides typed methods for Deal queries with soft-delete support.
 * Handles Deal stage transitions with history tracking.
 */

import { prisma } from './prisma';
import type {
  Deal,
  DealHistory,
  Prisma,
} from '@prisma/client';
import { randomUUID } from 'node:crypto';
import { isValidLossReason, getLossReasonLabel } from '../loss-reasons';
import { notifyDealStageChange, notifyDealLost } from '../notifications/events';

/**
 * Deal creation input type
 *
 * `id`/`number`/`createdAt`/`updatedAt` are auto-generated by the repository
 * when omitted, but callers may override them (e.g. tests, re-imports).
 */
export type DealCreateInput = Omit<
  Prisma.DealUncheckedCreateInput,
  'id' | 'number' | 'createdAt' | 'updatedAt'
> &
  Partial<Pick<Prisma.DealUncheckedCreateInput, 'id' | 'number' | 'createdAt' | 'updatedAt'>>;

/**
 * Deal update input type
 */
export type DealUpdateInput = Prisma.DealUncheckedUpdateInput;

/**
 * Deal findMany params type
 */
export type DealFindManyParams = {
  where?: Prisma.DealWhereInput;
  orderBy?: Prisma.DealOrderByWithRelationInput;
  skip?: number;
  take?: number;
  include?: Prisma.DealInclude;
};

/**
 * Repository for Deal CRUD operations
 */
export class DealRepository {
  /**
   * Generate deal number in format С-YYYY-NNNNN
   */
  private generateNumber(): string {
    const year = new Date().getFullYear();
    const random = Math.floor(Math.random() * 99999).toString().padStart(5, '0');
    return `С-${year}-${random}`;
  }

  /**
   * Find many deals with optional filtering
   * Automatically filters out soft-deleted records
   */
  async findMany(params?: DealFindManyParams): Promise<Deal[]> {
    const { where, ...rest } = params ?? {};

    // Явная аннотация типа нужна, чтобы разорвать рекурсивный вывод типов
    // (query-extension $extends + спред локального типа → TS2321 excessive stack depth).
    const args: Prisma.DealFindManyArgs = {
      ...rest,
      where: {
        ...where,
        deletedAt: null, // Always exclude soft-deleted
      },
    };

    return prisma.deal.findMany(args);
  }

  /**
   * Find a single deal by ID
   * Returns null if not found or soft-deleted.
   * When `include` is provided, the returned type is widened with the included
   * relations (mirrors Prisma's own `GetPayload` behaviour).
   */
  async findUnique<I extends Prisma.DealInclude>(
    id: string,
    include?: I
  ): Promise<Prisma.DealGetPayload<{ include: I }> | null> {
    const args: Prisma.DealFindFirstArgs = {
      where: { id, deletedAt: null },
      include,
    };
    return prisma.deal.findFirst(args) as Promise<Prisma.DealGetPayload<{ include: I }> | null>;
  }

  /**
   * Find deals by pipeline ID
   */
  async findByPipeline(pipelineId: string): Promise<Deal[]> {
    return this.findMany({
      where: { pipelineId },
      orderBy: { createdAt: 'desc' },
    });
  }

  /**
   * Find deals by stage ID
   */
  async findByStage(stageId: string): Promise<Deal[]> {
    return this.findMany({
      where: { stageId },
      orderBy: { createdAt: 'desc' },
    });
  }

  /**
   * Find deals by manager (owner)
   */
  async findByManager(managerId: string): Promise<Deal[]> {
    return this.findMany({
      where: { managerId },
      orderBy: { createdAt: 'desc' },
    });
  }

  /**
   * Find deals by contact
   */
  async findByContact(contactId: string): Promise<Deal[]> {
    return this.findMany({
      where: { contactId },
      orderBy: { createdAt: 'desc' },
    });
  }

  /**
   * Create a new deal
   * Generates UUID, number, and timestamps if not provided
   */
  async create(data: DealCreateInput): Promise<Deal> {
    const now = new Date();

    return prisma.deal.create({
      data: {
        ...data,
        id: data.id ?? randomUUID(),
        number: data.number ?? this.generateNumber(),
        createdAt: data.createdAt ?? now,
        updatedAt: data.updatedAt ?? now,
      },
    });
  }

  /**
   * Update an existing deal
   * Throws RecordNotFound if deal doesn't exist or is soft-deleted
   */
  async update(
    id: string,
    data: DealUpdateInput
  ): Promise<Deal> {
    // Verify deal exists and not deleted
    const existing = await this.findUnique(id);
    if (!existing) {
      throw new Error(`Deal with id ${id} not found`);
    }

    return prisma.deal.update({
      where: { id },
      data: {
        ...data,
        updatedAt: new Date(),
      },
    });
  }

  /**
   * Move deal to a different stage
   * Records the transition in DealHistory.
   * When moving to a lost stage, lossReason is mandatory (CRM-06).
   */
  async moveStage(
    dealId: string,
    toStageId: string,
    changedBy: string,
    comment?: string,
    lossReason?: string
  ): Promise<Deal> {
    const deal = await this.findUnique(dealId);
    if (!deal) {
      throw new Error(`Deal with id ${dealId} not found`);
    }

    const fromStageId = deal.stageId;

    // Resolve the target stage to check win/lost flags
    const stage = await prisma.dealStage.findUnique({
      where: { id: toStageId },
    });
    if (!stage) {
      throw new Error(`DealStage with id ${toStageId} not found`);
    }

    // CRM-06: loss reason is mandatory when moving to a lost stage
    if (stage.isLostStage) {
      if (!lossReason) {
        throw new Error('lossReason is required when moving to a lost stage');
      }
      if (!isValidLossReason(lossReason)) {
        throw new Error(`Invalid loss reason: ${lossReason}. Valid values: too_expensive, competitor, changed_mind, lost_contact, other`);
      }
    }

    // Record history
    await prisma.dealHistory.create({
      data: {
        id: randomUUID(),
        dealId,
        fromStageId,
        toStageId,
        comment: comment ?? null,
        changedBy,
        changedAt: new Date(),
      },
    });

    // Update deal stage + lossReason
    const updateData: Prisma.DealUncheckedUpdateInput = {
      stageId: toStageId,
      updatedAt: new Date(),
    };
    if (lossReason !== undefined) {
      updateData.lossReason = lossReason;
    }

    const updated = await prisma.deal.update({
      where: { id: dealId },
      data: updateData,
    });

    // Set closedAt if moved to won/lost stage
    if (stage.isWonStage || stage.isLostStage) {
      await prisma.deal.update({
        where: { id: dealId },
        data: {
          actualCloseDate: new Date(),
          closedAt: new Date(),
        },
      });
    }

    // PLAT-02: уведомления о смене стадии. Побочный эффект — не ломает транзакцию.
    // Только если стадия реально изменилась (защита от повторного перехода в ту же стадию).
    if (fromStageId === toStageId || !fromStageId) {
      return updated
    }

    // Нужны имена стадий для текста уведомления.
    const fromStage = fromStageId
      ? await prisma.dealStage.findUnique({ where: { id: fromStageId }, select: { name: true } })
      : null
    const dealTitle = deal.title ?? dealId
    void (async () => {
      try {
        if (stage.isLostStage && lossReason) {
          // Отказ → директору (найдём по роли).
          const director = await prisma.user.findFirst({
            where: { deletedAt: null, isActive: true, UserRole: { some: { Role: { code: 'director' } } } },
            select: { id: true },
          })
          if (director) {
            await notifyDealLost(director.id, dealTitle, getLossReasonLabel(lossReason), dealId)
          }
        } else if (deal.managerId) {
          // Обычная смена стадии → менеджеру сделки.
          await notifyDealStageChange(
            deal.managerId,
            dealTitle,
            fromStage?.name ?? '—',
            stage.name ?? toStageId,
            dealId
          )
        }
      } catch (err) {
        console.error('[moveStage] notification failed:', err)
      }
    })()

    return updated;
  }

  /**
   * Soft delete a deal by setting deletedAt timestamp
   * Does NOT actually delete the record from database
   */
  async softDelete(id: string): Promise<Deal> {
    // Verify deal exists and not already deleted
    const existing = await this.findUnique(id);
    if (!existing) {
      throw new Error(`Deal with id ${id} not found`);
    }

    return prisma.deal.update({
      where: { id },
      data: { deletedAt: new Date() },
    });
  }

  /**
   * Count deals matching criteria (excluding soft-deleted)
   */
  async count(where?: Prisma.DealWhereInput): Promise<number> {
    return prisma.deal.count({
      where: {
        ...where,
        deletedAt: null,
      },
    });
  }

  /**
   * Get deal history entries with related stage names and the user who made
   * the change, so the UI can render "От этапа A → этап B, user, время".
   */
  async getHistory(dealId: string) {
    // Явная аннотация типа нужна, чтобы разорвать рекурсивный вывод типов
    // (query-extension $extends + спред локального типа → TS2321 excessive stack depth).
    const args: Prisma.DealHistoryFindManyArgs = {
      where: { dealId },
      orderBy: { changedAt: 'desc' },
      include: {
        FromStage: { select: { id: true, name: true, color: true } },
        ToStage: { select: { id: true, name: true, color: true, isWonStage: true, isLostStage: true } },
        ChangedBy: { select: { id: true, name: true, email: true } },
      },
    };
    return prisma.dealHistory.findMany(args);
  }
}

/**
 * Singleton instance for use across the application
 */
export const deals = new DealRepository();

export default deals;
