/**
 * ProjectRepository - CRUD operations for Project model
 *
 * Provides typed methods for Project queries with soft-delete support.
 * Handles Project stage transitions and member management.
 */

import { prisma } from './prisma';
import type {
  Deal,
  Project,
  ProjectMember,
  ProjectStage,
  Prisma,
} from '@prisma/client';
import { randomUUID } from 'node:crypto';
import { nextProjectNumber } from './sequence';
import { ConflictError } from './errors';

/** Результат проверки готовности проекта к закрытию (PROJ-13). */
export interface ClosureCondition {
  key: 'act_signed' | 'client_paid' | 'supplier_invoices_paid' | 'designer_bonus_paid';
  label: string;
  met: boolean;
  detail: string;
}

export interface ClosureReadiness {
  ready: boolean;
  conditions: ClosureCondition[];
}

/**
 * Project creation input type
 *
 * `id`/`createdAt`/`updatedAt` are auto-generated by the repository when
 * omitted, but callers may override them (e.g. tests, re-imports).
 * `externalNumber` is also auto-generated when omitted.
 */
export type ProjectCreateInput = Omit<
  Prisma.ProjectUncheckedCreateInput,
  'id' | 'createdAt' | 'updatedAt' | 'externalNumber'
> &
  Partial<
    Pick<Prisma.ProjectUncheckedCreateInput, 'id' | 'createdAt' | 'updatedAt' | 'externalNumber'>
  >;

/**
 * Project update input type
 */
export type ProjectUpdateInput = Prisma.ProjectUncheckedUpdateInput;

/**
 * Project findMany params type
 */
export type ProjectFindManyParams = {
  where?: Prisma.ProjectWhereInput;
  orderBy?: Prisma.ProjectOrderByWithRelationInput;
  skip?: number;
  take?: number;
  include?: Prisma.ProjectInclude;
};

/**
 * Repository for Project CRUD operations
 */
export class ProjectRepository {
  /**
   * Find many projects with optional filtering
   * Automatically filters out soft-deleted records
   */
  async findMany(params?: ProjectFindManyParams): Promise<Project[]> {
    const { where, ...rest } = params ?? {};

    // Явная аннотация типа нужна, чтобы разорвать рекурсивный вывод типов
    // (query-extension $extends + спред локального типа → TS2321 excessive stack depth).
    const args: Prisma.ProjectFindManyArgs = {
      ...rest,
      where: {
        ...where,
        deletedAt: null, // Always exclude soft-deleted
      },
    };

    return prisma.project.findMany(args);
  }

  /**
   * Find a single project by ID
   * Returns null if not found or soft-deleted
   */
  async findUnique<I extends Prisma.ProjectInclude>(
    id: string,
    include?: I
  ): Promise<Prisma.ProjectGetPayload<{ include: I }> | null> {
    // Явная аннотация типа нужна, чтобы разорвать рекурсивный вывод типов
    // (query-extension $extends → TS2321 excessive stack depth).
    const args: Prisma.ProjectFindFirstArgs = {
      where: { id, deletedAt: null },
      include,
    };
    return prisma.project.findFirst(args) as Promise<
      Prisma.ProjectGetPayload<{ include: I }> | null
    >;
  }

  /**
   * Find projects by status
   */
  async findByStatus(status: string): Promise<Project[]> {
    return this.findMany({
      where: { status },
      orderBy: { createdAt: 'desc' },
    });
  }

  /**
   * Find projects by manager (owner)
   */
  async findByManager(managerId: string): Promise<Project[]> {
    return this.findMany({
      where: { managerId },
      orderBy: { createdAt: 'desc' },
    });
  }

  /**
   * Find projects by contact
   */
  async findByContact(contactId: string): Promise<Project[]> {
    return this.findMany({
      where: { contactId },
      orderBy: { createdAt: 'desc' },
    });
  }

  /**
   * Find projects by deal
   */
  async findByDeal(dealId: string): Promise<Project[]> {
    return this.findMany({
      where: { dealId },
      orderBy: { createdAt: 'desc' },
    });
  }

  /**
   * Create a new project
   * Generates UUID and timestamps if not provided
   */
  async create(data: ProjectCreateInput): Promise<Project> {
    const now = new Date();

    return prisma.project.create({
      data: {
        ...data,
        id: data.id ?? randomUUID(),
        externalNumber: data.externalNumber ?? await nextProjectNumber(prisma, new Date().getFullYear()),
        createdAt: data.createdAt ?? now,
        updatedAt: data.updatedAt ?? now,
      },
    });
  }

  /**
   * Generate external project number in format ПМ{YYYY}-{NNNN}
   * (delegates to shared sequence generator).
   */
  private async generateExternalNumber(): Promise<string> {
    return nextProjectNumber(prisma, new Date().getFullYear());
  }

  /**
   * Update an existing project
   * Throws Error if project doesn't exist or is soft-deleted
   */
  async update(
    id: string,
    data: ProjectUpdateInput,
    changedById?: string
  ): Promise<Project> {
    const existing = await this.findUnique(id);
    if (!existing) {
      throw new Error(`Project with id ${id} not found`);
    }

    const newStatus = (data as Record<string,unknown>).status as string | undefined;
    const shouldRecordHistory = newStatus && newStatus !== existing.status && changedById;

    const result = await prisma.$transaction(async (tx) => {
      const updated = await tx.project.update({
        where: { id },
        data: { ...data, updatedAt: new Date() },
      });

      if (shouldRecordHistory) {
        await tx.projectStatusHistory.create({
          data: {
            id: randomUUID(),
            projectId: id,
            fromStatus: existing.status,
            toStatus: newStatus!,
            changedById,
            changedAt: new Date(),
            createdAt: new Date(),
          },
        });
      }

      return updated;
    });

    return result;
  }

  /**
   * Soft delete a project by setting deletedAt timestamp
   * Does NOT actually delete the record from database
   */
  async softDelete(id: string): Promise<Project> {
    // Verify project exists and not already deleted
    const existing = await this.findUnique(id);
    if (!existing) {
      throw new Error(`Project with id ${id} not found`);
    }

    return prisma.project.update({
      where: { id },
      data: { deletedAt: new Date() },
    });
  }

  /**
   * Count projects matching criteria (excluding soft-deleted)
   */
  async count(where?: Prisma.ProjectWhereInput): Promise<number> {
    return prisma.project.count({
      where: {
        ...where,
        deletedAt: null,
      },
    });
  }

  /**
   * Create a project stage
   */
  async createStage(
    projectId: string,
    data: Omit<Prisma.ProjectStageUncheckedCreateInput, 'id' | 'projectId'>
  ): Promise<ProjectStage> {
    return prisma.projectStage.create({
      data: {
        ...data,
        id: randomUUID(),
        projectId,
      },
    });
  }

  /**
   * Update a project stage
   */
  async updateStage(
    stageId: string,
    data: Prisma.ProjectStageUncheckedUpdateInput
  ): Promise<ProjectStage> {
    return prisma.projectStage.update({
      where: { id: stageId },
      data,
    });
  }

  /**
   * Find stages for a project
   */
  async findStages(projectId: string): Promise<ProjectStage[]> {
    return prisma.projectStage.findMany({
      where: { projectId },
      orderBy: { order: 'asc' },
    });
  }

  /**
   * Add a member to a project
   */
  async addMember(
    projectId: string,
    userId: string,
    role: string = 'member'
  ): Promise<ProjectMember> {
    return prisma.projectMember.create({
      data: {
        id: randomUUID(),
        projectId,
        userId,
        role,
        joinedAt: new Date(),
      },
    });
  }

  /**
   * Remove a member from a project (sets leftAt timestamp)
   */
  async removeMember(projectId: string, userId: string): Promise<ProjectMember> {
    const member = await prisma.projectMember.findUnique({
      where: { projectId_userId: { projectId, userId } },
    });

    if (!member) {
      throw new Error(`Member ${userId} not found in project ${projectId}`);
    }

    return prisma.projectMember.update({
      where: { projectId_userId: { projectId, userId } },
      data: { leftAt: new Date() },
    });
  }

  /**
   * Find members for a project
   */
  async findMembers(
    projectId: string
  ): Promise<
    Prisma.ProjectMemberGetPayload<{
      include: { User: { select: { id: true; name: true; email: true } } };
    }>[]
  > {
    const args: Prisma.ProjectMemberFindManyArgs = {
      where: {
        projectId,
        leftAt: null, // Only active members
      },
      include: {
        User: {
          select: {
            id: true,
            name: true,
            email: true,
          },
        },
      },
    };
    return prisma.projectMember.findMany(args) as Promise<
      Prisma.ProjectMemberGetPayload<{
        include: { User: { select: { id: true; name: true; email: true } } };
      }>[]
    >;
  }

  /**
   * Проверить готовность проекта к закрытию (PROJ-13).
   *
   * Возвращает чек-лист из четырёх условий:
   *  1. Акт приёмки подписан.
   *  2. Все деньги клиента получены (сумма income >= contractAmount).
   *  3. Все счета поставщиков/производств оплачены.
   *  4. Бонус дизайнеру выплачен.
   *
   * Готовность (`ready`) = выполнены все условия. Само закрытие не блокируется
   * жёстко — UI показывает предупреждения и допускает закрытие с override.
   */
  async getClosureReadiness(projectId: string): Promise<ClosureReadiness> {
    const project = await prisma.project.findFirst({
      where: { id: projectId, deletedAt: null },
      select: {
        id: true,
        contractAmount: true,
        AcceptanceAct: { select: { status: true, signedAt: true } },
        DesignerBonus: { select: { status: true } },
      },
    });

    if (!project) {
      throw new Error(`Project with id ${projectId} not found`);
    }

    // 1. Акт подписан.
    const actSigned = project.AcceptanceAct?.status === 'signed' || !!project.AcceptanceAct?.signedAt;

    // 2. Все деньги клиента получены: сумма income-транзакций проекта >= contractAmount.
    const incomeAgg = await prisma.transaction.aggregate({
      where: { projectId, type: 'income', deletedAt: null },
      _sum: { amount: true },
    });
    const incomeReceived = Number(incomeAgg._sum.amount ?? 0);
    const contractAmount = Number(project.contractAmount ?? 0);
    const clientPaid = incomeReceived >= contractAmount;

    // 3. Все счета поставщиков оплачены: нет неоплаченных (paidAt IS NULL).
    const unpaidInvoices = await prisma.invoice.count({
      where: { projectId, paidAt: null },
    });
    const supplierInvoicesPaid = unpaidInvoices === 0;

    // 4. Бонус дизайнеру выплачен. Если бонуса нет — условие считается невыполненным.
    const bonusPaid = project.DesignerBonus?.status === 'paid';

    const formatRub = (n: number) =>
      new Intl.NumberFormat('ru-RU', { style: 'currency', currency: 'RUB', maximumFractionDigits: 0 }).format(n);

    const conditions: ClosureCondition[] = [
      {
        key: 'act_signed',
        label: 'Акт приёмки подписан',
        met: actSigned,
        detail: actSigned ? 'Акт подписан' : 'Акт ещё не подписан',
      },
      {
        key: 'client_paid',
        label: 'Все деньги клиента получены',
        met: clientPaid,
        detail: clientPaid
          ? `Получено ${formatRub(incomeReceived)} из ${formatRub(contractAmount)}`
          : `Получено ${formatRub(incomeReceived)}, не хватает ${formatRub(Math.max(0, contractAmount - incomeReceived))}`,
      },
      {
        key: 'supplier_invoices_paid',
        label: 'Все счета поставщикам оплачены',
        met: supplierInvoicesPaid,
        detail: supplierInvoicesPaid
          ? 'Неоплаченных счетов нет'
          : `${unpaidInvoices} ${unpaidInvoices === 1 ? 'счёт' : 'счёта/счетов'} не оплачено`,
      },
      {
        key: 'designer_bonus_paid',
        label: 'Бонус дизайнеру выплачен',
        met: bonusPaid,
        detail: bonusPaid ? 'Бонус выплачен' : 'Бонус не выплачен (или не заведён)',
      },
    ];

    return {
      ready: conditions.every((c) => c.met),
      conditions,
    };
  }

  /**
   * Complete a project and cascade the completion to the related Deal.
   * Validates all project stages are completed first.
   * Checks closure readiness (PROJ-13) unless `overrideUnmet` is set.
   * Records warranty period on completion (PROJ-14: 2 года + фурнитура).
   * Uses Prisma transaction to atomically update both Project and Deal.
   *
   * @param projectId - The project ID to complete
   * @param userId - The user ID performing the completion (for DealHistory)
   * @param overrideUnmet - When true, allow completion even if closure conditions are unmet
   * @returns Object containing updated Project and Deal (if exists) plus readiness
   * @throws Error if project not found, stages not completed, or deal won stage not found
   * @throws ConflictError if closure conditions unmet and overrideUnmet is false
   */
  async completeWithCascade(
    projectId: string,
    userId: string,
    overrideUnmet: boolean = false
  ): Promise<{ project: Project; deal: Deal | null; readiness: ClosureReadiness }> {
    const now = new Date();

    // Проверка готовности к закрытию (PROJ-13). Жёстко не блокируем — см. overrideUnmet.
    const readiness = await this.getClosureReadiness(projectId);
    if (!readiness.ready && !overrideUnmet) {
      const unmet = readiness.conditions
        .filter((c) => !c.met)
        .map((c) => c.label)
        .join('; ');
      throw new ConflictError(
        `Невыполненные условия закрытия: ${unmet}. Закройте с override, чтобы проигнорировать.`
      );
    }

    // Use transaction to ensure atomic updates
    return prisma.$transaction(async (tx) => {
      // 1. Fetch project with stages to validate completion
      const project = await tx.project.findFirst({
        where: { id: projectId, deletedAt: null },
        include: {
          ProjectStage: {
            orderBy: { order: 'asc' },
          },
        },
      });

      if (!project) {
        throw new Error(`Project with id ${projectId} not found`);
      }

      // 2. Validate all stages are completed
      const incompleteStages = project.ProjectStage.filter(
        (stage) => stage.status !== 'completed'
      );
      if (incompleteStages.length > 0) {
        const stageNames = incompleteStages.map((s) => s.name).join(', ');
        throw new Error(
          `Cannot complete project: incomplete stages: ${stageNames}`
        );
      }

      // 3. Find the won stage for the deal's pipeline
      let wonStageId: string | null = null;
      let deal: Deal | null = null;

      if (project.dealId) {
        // Fetch the deal to get its pipeline
        const existingDeal = await tx.deal.findFirst({
          where: { id: project.dealId, deletedAt: null },
          include: { DealStage: true },
        });

        if (!existingDeal) {
          throw new Error(`Deal with id ${project.dealId} not found`);
        }

        // Find the won stage in the same pipeline
        const wonStage = await tx.dealStage.findFirst({
          where: {
            pipelineId: existingDeal.pipelineId,
            isWonStage: true,
          },
        });

        if (!wonStage) {
          throw new Error(
            `No won stage found in pipeline ${existingDeal.pipelineId}`
          );
        }

        wonStageId = wonStage.id;
        deal = existingDeal;
      }

      // 4. Update project status to completed + record warranty period (PROJ-14)
      const warrantyEndDate = new Date(now);
      warrantyEndDate.setFullYear(warrantyEndDate.getFullYear() + 2);

      const updatedProject = await tx.project.update({
        where: { id: projectId },
        data: {
          status: 'completed',
          completedAt: now,
          // PROJ-14: гарантия 2 года + фурнитура по гарантии производителя.
          warrantyStartDate: project.warrantyStartDate ?? now,
          warrantyEndDate: project.warrantyEndDate ?? warrantyEndDate,
          warrantyNotes: project.warrantyNotes ?? '2 года; фурнитура — по гарантии производителя',
          updatedAt: now,
        },
      });

      // Record ProjectStatusHistory for the completion
      await tx.projectStatusHistory.create({
        data: {
          id: randomUUID(),
          projectId,
          fromStatus: project.status,
          toStatus: 'completed',
          changedById: userId,
          reason: 'Проект завершён (все этапы выполнены)',
          changedAt: now,
          createdAt: now,
        },
      });

      // 5. If deal exists, move it to won stage and set closedAt
      let updatedDeal: Deal | null = null;
      if (deal && wonStageId) {
        const fromStageId = deal.stageId;

        // Record deal history for the stage move
        await tx.dealHistory.create({
          data: {
            id: randomUUID(),
            dealId: deal.id,
            fromStageId,
            toStageId: wonStageId,
            changedBy: userId,
            changedAt: now,
          },
        });

        // Update deal to won stage and set closed timestamps
        updatedDeal = await tx.deal.update({
          where: { id: deal.id },
          data: {
            stageId: wonStageId,
            actualCloseDate: now,
            closedAt: now,
            updatedAt: now,
          },
        });
      }

      return {
        project: updatedProject,
        deal: updatedDeal,
        readiness,
      };
    });
  }

  /**
   * Get project status history entries with the user who made each change.
   */
  async getHistory(projectId: string) {
    return prisma.projectStatusHistory.findMany({
      where: { projectId },
      orderBy: { changedAt: 'desc' },
      include: {
        User: { select: { id: true, name: true, email: true } },
      },
    });
  }
}

/**
 * Lightweight helper: returns the managerId of a project (or null if not found / no manager).
 * Used by RBAC ownership checks in child-entity endpoints (invoices, bom, deliveries, etc.)
 */
export async function getProjectManagerId(projectId: string): Promise<string | null> {
  const p = await prisma.project.findUnique({
    where: { id: projectId },
    select: { managerId: true },
  });
  return p?.managerId ?? null;
}

/**
 * Singleton instance for use across the application
 */
export const projects = new ProjectRepository();

export default projects;
