/**
 * ProjectRepository - CRUD operations for Project model
 *
 * Provides typed methods for Project queries with soft-delete support.
 * Handles Project stage transitions and member management.
 */

import { prisma } from './prisma';
import type {
  Deal,
  Project,
  ProjectMember,
  ProjectStage,
  Prisma,
} from '@prisma/client';
import { randomUUID } from 'node:crypto';

/**
 * Project creation input type
 *
 * `id`/`createdAt`/`updatedAt` are auto-generated by the repository when
 * omitted, but callers may override them (e.g. tests, re-imports).
 * `externalNumber` is also auto-generated when omitted.
 */
export type ProjectCreateInput = Omit<
  Prisma.ProjectUncheckedCreateInput,
  'id' | 'createdAt' | 'updatedAt' | 'externalNumber'
> &
  Partial<
    Pick<Prisma.ProjectUncheckedCreateInput, 'id' | 'createdAt' | 'updatedAt' | 'externalNumber'>
  >;

/**
 * Project update input type
 */
export type ProjectUpdateInput = Prisma.ProjectUncheckedUpdateInput;

/**
 * Project findMany params type
 */
export type ProjectFindManyParams = {
  where?: Prisma.ProjectWhereInput;
  orderBy?: Prisma.ProjectOrderByWithRelationInput;
  skip?: number;
  take?: number;
  include?: Prisma.ProjectInclude;
};

/**
 * Repository for Project CRUD operations
 */
export class ProjectRepository {
  /**
   * Find many projects with optional filtering
   * Automatically filters out soft-deleted records
   */
  async findMany(params?: ProjectFindManyParams): Promise<Project[]> {
    const { where, ...rest } = params ?? {};

    // Явная аннотация типа нужна, чтобы разорвать рекурсивный вывод типов
    // (query-extension $extends + спред локального типа → TS2321 excessive stack depth).
    const args: Prisma.ProjectFindManyArgs = {
      ...rest,
      where: {
        ...where,
        deletedAt: null, // Always exclude soft-deleted
      },
    };

    return prisma.project.findMany(args);
  }

  /**
   * Find a single project by ID
   * Returns null if not found or soft-deleted
   */
  async findUnique<I extends Prisma.ProjectInclude>(
    id: string,
    include?: I
  ): Promise<Prisma.ProjectGetPayload<{ include: I }> | null> {
    // Явная аннотация типа нужна, чтобы разорвать рекурсивный вывод типов
    // (query-extension $extends → TS2321 excessive stack depth).
    const args: Prisma.ProjectFindFirstArgs = {
      where: { id, deletedAt: null },
      include,
    };
    return prisma.project.findFirst(args) as Promise<
      Prisma.ProjectGetPayload<{ include: I }> | null
    >;
  }

  /**
   * Find projects by status
   */
  async findByStatus(status: string): Promise<Project[]> {
    return this.findMany({
      where: { status },
      orderBy: { createdAt: 'desc' },
    });
  }

  /**
   * Find projects by manager (owner)
   */
  async findByManager(managerId: string): Promise<Project[]> {
    return this.findMany({
      where: { managerId },
      orderBy: { createdAt: 'desc' },
    });
  }

  /**
   * Find projects by contact
   */
  async findByContact(contactId: string): Promise<Project[]> {
    return this.findMany({
      where: { contactId },
      orderBy: { createdAt: 'desc' },
    });
  }

  /**
   * Find projects by deal
   */
  async findByDeal(dealId: string): Promise<Project[]> {
    return this.findMany({
      where: { dealId },
      orderBy: { createdAt: 'desc' },
    });
  }

  /**
   * Create a new project
   * Generates UUID and timestamps if not provided
   */
  async create(data: ProjectCreateInput): Promise<Project> {
    const now = new Date();

    return prisma.project.create({
      data: {
        ...data,
        id: data.id ?? randomUUID(),
        externalNumber: data.externalNumber ?? this.generateExternalNumber(),
        createdAt: data.createdAt ?? now,
        updatedAt: data.updatedAt ?? now,
      },
    });
  }

  /**
   * Generate external project number in format PRJ-YYYY-NNNNN
   */
  private generateExternalNumber(): string {
    const year = new Date().getFullYear();
    const random = Math.floor(Math.random() * 99999).toString().padStart(5, '0');
    return `PRJ-${year}-${random}`;
  }

  /**
   * Update an existing project
   * Throws Error if project doesn't exist or is soft-deleted
   */
  async update(
    id: string,
    data: ProjectUpdateInput
  ): Promise<Project> {
    // Verify project exists and not deleted
    const existing = await this.findUnique(id);
    if (!existing) {
      throw new Error(`Project with id ${id} not found`);
    }

    return prisma.project.update({
      where: { id },
      data: {
        ...data,
        updatedAt: new Date(),
      },
    });
  }

  /**
   * Soft delete a project by setting deletedAt timestamp
   * Does NOT actually delete the record from database
   */
  async softDelete(id: string): Promise<Project> {
    // Verify project exists and not already deleted
    const existing = await this.findUnique(id);
    if (!existing) {
      throw new Error(`Project with id ${id} not found`);
    }

    return prisma.project.update({
      where: { id },
      data: { deletedAt: new Date() },
    });
  }

  /**
   * Count projects matching criteria (excluding soft-deleted)
   */
  async count(where?: Prisma.ProjectWhereInput): Promise<number> {
    return prisma.project.count({
      where: {
        ...where,
        deletedAt: null,
      },
    });
  }

  /**
   * Create a project stage
   */
  async createStage(
    projectId: string,
    data: Omit<Prisma.ProjectStageUncheckedCreateInput, 'id' | 'projectId'>
  ): Promise<ProjectStage> {
    return prisma.projectStage.create({
      data: {
        ...data,
        id: randomUUID(),
        projectId,
      },
    });
  }

  /**
   * Update a project stage
   */
  async updateStage(
    stageId: string,
    data: Prisma.ProjectStageUncheckedUpdateInput
  ): Promise<ProjectStage> {
    return prisma.projectStage.update({
      where: { id: stageId },
      data,
    });
  }

  /**
   * Find stages for a project
   */
  async findStages(projectId: string): Promise<ProjectStage[]> {
    return prisma.projectStage.findMany({
      where: { projectId },
      orderBy: { order: 'asc' },
    });
  }

  /**
   * Add a member to a project
   */
  async addMember(
    projectId: string,
    userId: string,
    role: string = 'member'
  ): Promise<ProjectMember> {
    return prisma.projectMember.create({
      data: {
        id: randomUUID(),
        projectId,
        userId,
        role,
        joinedAt: new Date(),
      },
    });
  }

  /**
   * Remove a member from a project (sets leftAt timestamp)
   */
  async removeMember(projectId: string, userId: string): Promise<ProjectMember> {
    const member = await prisma.projectMember.findUnique({
      where: { projectId_userId: { projectId, userId } },
    });

    if (!member) {
      throw new Error(`Member ${userId} not found in project ${projectId}`);
    }

    return prisma.projectMember.update({
      where: { projectId_userId: { projectId, userId } },
      data: { leftAt: new Date() },
    });
  }

  /**
   * Find members for a project
   */
  async findMembers(
    projectId: string
  ): Promise<
    Prisma.ProjectMemberGetPayload<{
      include: { User: { select: { id: true; name: true; email: true } } };
    }>[]
  > {
    const args: Prisma.ProjectMemberFindManyArgs = {
      where: {
        projectId,
        leftAt: null, // Only active members
      },
      include: {
        User: {
          select: {
            id: true,
            name: true,
            email: true,
          },
        },
      },
    };
    return prisma.projectMember.findMany(args) as Promise<
      Prisma.ProjectMemberGetPayload<{
        include: { User: { select: { id: true; name: true; email: true } } };
      }>[]
    >;
  }

  /**
   * Complete a project and cascade the completion to the related Deal.
   * Validates all project stages are completed first.
   * Uses Prisma transaction to atomically update both Project and Deal.
   *
   * @param projectId - The project ID to complete
   * @param userId - The user ID performing the completion (for DealHistory)
   * @returns Object containing updated Project and Deal (if exists)
   * @throws Error if project not found, stages not completed, or deal won stage not found
   */
  async completeWithCascade(
    projectId: string,
    userId: string
  ): Promise<{ project: Project; deal: Deal | null }> {
    const now = new Date();

    // Use transaction to ensure atomic updates
    return prisma.$transaction(async (tx) => {
      // 1. Fetch project with stages to validate completion
      const project = await tx.project.findFirst({
        where: { id: projectId, deletedAt: null },
        include: {
          ProjectStage: {
            orderBy: { order: 'asc' },
          },
        },
      });

      if (!project) {
        throw new Error(`Project with id ${projectId} not found`);
      }

      // 2. Validate all stages are completed
      const incompleteStages = project.ProjectStage.filter(
        (stage) => stage.status !== 'completed'
      );
      if (incompleteStages.length > 0) {
        const stageNames = incompleteStages.map((s) => s.name).join(', ');
        throw new Error(
          `Cannot complete project: incomplete stages: ${stageNames}`
        );
      }

      // 3. Find the won stage for the deal's pipeline
      let wonStageId: string | null = null;
      let deal: Deal | null = null;

      if (project.dealId) {
        // Fetch the deal to get its pipeline
        const existingDeal = await tx.deal.findFirst({
          where: { id: project.dealId, deletedAt: null },
          include: { DealStage: true },
        });

        if (!existingDeal) {
          throw new Error(`Deal with id ${project.dealId} not found`);
        }

        // Find the won stage in the same pipeline
        const wonStage = await tx.dealStage.findFirst({
          where: {
            pipelineId: existingDeal.pipelineId,
            isWonStage: true,
          },
        });

        if (!wonStage) {
          throw new Error(
            `No won stage found in pipeline ${existingDeal.pipelineId}`
          );
        }

        wonStageId = wonStage.id;
        deal = existingDeal;
      }

      // 4. Update project status to completed
      const updatedProject = await tx.project.update({
        where: { id: projectId },
        data: {
          status: 'completed',
          completedAt: now,
          updatedAt: now,
        },
      });

      // 5. If deal exists, move it to won stage and set closedAt
      let updatedDeal: Deal | null = null;
      if (deal && wonStageId) {
        const fromStageId = deal.stageId;

        // Record deal history for the stage move
        await tx.dealHistory.create({
          data: {
            id: randomUUID(),
            dealId: deal.id,
            fromStageId,
            toStageId: wonStageId,
            changedBy: userId,
            changedAt: now,
          },
        });

        // Update deal to won stage and set closed timestamps
        updatedDeal = await tx.deal.update({
          where: { id: deal.id },
          data: {
            stageId: wonStageId,
            actualCloseDate: now,
            closedAt: now,
            updatedAt: now,
          },
        });
      }

      return {
        project: updatedProject,
        deal: updatedDeal,
      };
    });
  }
}

/**
 * Singleton instance for use across the application
 */
export const projects = new ProjectRepository();

export default projects;
